// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/webmin7761/go-school/homework/engineering/internal/biz"
	"github.com/webmin7761/go-school/homework/engineering/internal/conf"
	"github.com/webmin7761/go-school/homework/engineering/internal/data"
	"github.com/webmin7761/go-school/homework/engineering/internal/server"
	"github.com/webmin7761/go-school/homework/engineering/internal/service"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, traceTracerProvider trace.TracerProvider, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	fareRepo := data.NewFareRepo(dataData, logger)
	fareUsecase := biz.NewFareUsecase(fareRepo, logger)
	fareService := service.NewFareService(fareUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, traceTracerProvider, fareService)
	grpcServer := server.NewGRPCServer(confServer, traceTracerProvider, fareService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
