// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: fare.proto

package fare

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PassageTypes int32

const (
	PassageTypes_ADT PassageTypes = 0 //成人
	PassageTypes_CHD PassageTypes = 1 //儿童
	PassageTypes_INF PassageTypes = 2 //婴儿
)

// Enum value maps for PassageTypes.
var (
	PassageTypes_name = map[int32]string{
		0: "ADT",
		1: "CHD",
		2: "INF",
	}
	PassageTypes_value = map[string]int32{
		"ADT": 0,
		"CHD": 1,
		"INF": 2,
	}
)

func (x PassageTypes) Enum() *PassageTypes {
	p := new(PassageTypes)
	*p = x
	return p
}

func (x PassageTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PassageTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_fare_proto_enumTypes[0].Descriptor()
}

func (PassageTypes) Type() protoreflect.EnumType {
	return &file_fare_proto_enumTypes[0]
}

func (x PassageTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PassageTypes.Descriptor instead.
func (PassageTypes) EnumDescriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{0}
}

type ServiceLevel int32

const (
	ServiceLevel_First    ServiceLevel = 0 //头等
	ServiceLevel_Business ServiceLevel = 1 //公务
	ServiceLevel_Economy  ServiceLevel = 2 //经济
)

// Enum value maps for ServiceLevel.
var (
	ServiceLevel_name = map[int32]string{
		0: "First",
		1: "Business",
		2: "Economy",
	}
	ServiceLevel_value = map[string]int32{
		"First":    0,
		"Business": 1,
		"Economy":  2,
	}
)

func (x ServiceLevel) Enum() *ServiceLevel {
	p := new(ServiceLevel)
	*p = x
	return p
}

func (x ServiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_fare_proto_enumTypes[1].Descriptor()
}

func (ServiceLevel) Type() protoreflect.EnumType {
	return &file_fare_proto_enumTypes[1]
}

func (x ServiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceLevel.Descriptor instead.
func (ServiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{1}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//0 - 成功，其它 - 失败
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	//失败信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Fare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//起飞机场
	OrgAirport string `protobuf:"bytes,2,opt,name=org_airport,json=orgAirport,proto3" json:"org_airport,omitempty"`
	//到达机场
	ArrAirport string `protobuf:"bytes,3,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	//乘客类型
	PassageType PassageTypes `protobuf:"varint,4,opt,name=passage_type,json=passageType,proto3,enum=fare.PassageTypes" json:"passage_type,omitempty"`
	//旅行开始日期
	FirstTravelDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_travel_date,json=firstTravelDate,proto3" json:"first_travel_date,omitempty"`
	//旅行结束日期
	LastTravelDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_travel_date,json=lastTravelDate,proto3" json:"last_travel_date,omitempty"`
	//价格
	Amount *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Fare) Reset() {
	*x = Fare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fare) ProtoMessage() {}

func (x *Fare) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fare.ProtoReflect.Descriptor instead.
func (*Fare) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{1}
}

func (x *Fare) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fare) GetOrgAirport() string {
	if x != nil {
		return x.OrgAirport
	}
	return ""
}

func (x *Fare) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *Fare) GetPassageType() PassageTypes {
	if x != nil {
		return x.PassageType
	}
	return PassageTypes_ADT
}

func (x *Fare) GetFirstTravelDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTravelDate
	}
	return nil
}

func (x *Fare) GetLastTravelDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTravelDate
	}
	return nil
}

func (x *Fare) GetAmount() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Amount
	}
	return nil
}

type CreateFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare *Fare `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *CreateFareRequest) Reset() {
	*x = CreateFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFareRequest) ProtoMessage() {}

func (x *CreateFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFareRequest.ProtoReflect.Descriptor instead.
func (*CreateFareRequest) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFareRequest) GetFare() *Fare {
	if x != nil {
		return x.Fare
	}
	return nil
}

type CreateFareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//处理结果
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateFareReply) Reset() {
	*x = CreateFareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFareReply) ProtoMessage() {}

func (x *CreateFareReply) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFareReply.ProtoReflect.Descriptor instead.
func (*CreateFareReply) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFareReply) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare *Fare `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *UpdateFareRequest) Reset() {
	*x = UpdateFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFareRequest) ProtoMessage() {}

func (x *UpdateFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFareRequest.ProtoReflect.Descriptor instead.
func (*UpdateFareRequest) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFareRequest) GetFare() *Fare {
	if x != nil {
		return x.Fare
	}
	return nil
}

type UpdateFareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fare *Fare `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
}

func (x *UpdateFareReply) Reset() {
	*x = UpdateFareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFareReply) ProtoMessage() {}

func (x *UpdateFareReply) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFareReply.ProtoReflect.Descriptor instead.
func (*UpdateFareReply) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFareReply) GetFare() *Fare {
	if x != nil {
		return x.Fare
	}
	return nil
}

type DeleteFareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFareRequest) Reset() {
	*x = DeleteFareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFareRequest) ProtoMessage() {}

func (x *DeleteFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFareRequest.ProtoReflect.Descriptor instead.
func (*DeleteFareRequest) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFareRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFareReply) Reset() {
	*x = DeleteFareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFareReply) ProtoMessage() {}

func (x *DeleteFareReply) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFareReply.ProtoReflect.Descriptor instead.
func (*DeleteFareReply) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{7}
}

//机票销售价格计算请求
type PricingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//起飞机场
	OrgAirport string `protobuf:"bytes,1,opt,name=org_airport,json=orgAirport,proto3" json:"org_airport,omitempty"`
	//到达机场
	ArrAirport string `protobuf:"bytes,2,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	//航班日期
	FlightDatetime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=flight_datetime,json=flightDatetime,proto3" json:"flight_datetime,omitempty"`
	//乘客类型
	PassageType PassageTypes `protobuf:"varint,4,opt,name=passage_type,json=passageType,proto3,enum=fare.PassageTypes" json:"passage_type,omitempty"`
}

func (x *PricingRequest) Reset() {
	*x = PricingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRequest) ProtoMessage() {}

func (x *PricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRequest.ProtoReflect.Descriptor instead.
func (*PricingRequest) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{8}
}

func (x *PricingRequest) GetOrgAirport() string {
	if x != nil {
		return x.OrgAirport
	}
	return ""
}

func (x *PricingRequest) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *PricingRequest) GetFlightDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.FlightDatetime
	}
	return nil
}

func (x *PricingRequest) GetPassageType() PassageTypes {
	if x != nil {
		return x.PassageType
	}
	return PassageTypes_ADT
}

//机票销售价格计算结果
type PricingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//处理结果
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	//起飞机场
	OrgAirport string `protobuf:"bytes,2,opt,name=org_airport,json=orgAirport,proto3" json:"org_airport,omitempty"`
	//到达机场
	ArrAirport string `protobuf:"bytes,3,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	//航班日期
	FlightDatetime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=flight_datetime,json=flightDatetime,proto3" json:"flight_datetime,omitempty"`
	//乘客类型
	PassageType PassageTypes `protobuf:"varint,5,opt,name=passage_type,json=passageType,proto3,enum=fare.PassageTypes" json:"passage_type,omitempty"`
	//价格
	Amount *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PricingResponse) Reset() {
	*x = PricingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fare_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PricingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingResponse) ProtoMessage() {}

func (x *PricingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fare_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingResponse.ProtoReflect.Descriptor instead.
func (*PricingResponse) Descriptor() ([]byte, []int) {
	return file_fare_proto_rawDescGZIP(), []int{9}
}

func (x *PricingResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PricingResponse) GetOrgAirport() string {
	if x != nil {
		return x.OrgAirport
	}
	return ""
}

func (x *PricingResponse) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *PricingResponse) GetFlightDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.FlightDatetime
	}
	return nil
}

func (x *PricingResponse) GetPassageType() PassageTypes {
	if x != nil {
		return x.PassageType
	}
	return PassageTypes_ADT
}

func (x *PricingResponse) GetAmount() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_fare_proto protoreflect.FileDescriptor

var file_fare_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x61,
	0x72, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd3, 0x02, 0x0a, 0x04,
	0x46, 0x61, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x67, 0x5f, 0x61, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x67, 0x41, 0x69,
	0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x5f, 0x61, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x72, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x66,
	0x61, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x46, 0x0a,
	0x11, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x46, 0x61, 0x72, 0x65,
	0x52, 0x04, 0x66, 0x61, 0x72, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x61, 0x72, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x33, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x46, 0x61, 0x72, 0x65, 0x52, 0x04,
	0x66, 0x61, 0x72, 0x65, 0x22, 0x31, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x46, 0x61, 0x72,
	0x65, 0x52, 0x04, 0x66, 0x61, 0x72, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0xce, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x67, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x67, 0x41, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x72, 0x41, 0x69, 0x72,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x61, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xab, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72,
	0x67, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x72, 0x67, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x72, 0x72, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x72, 0x72, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x43, 0x0a, 0x0f,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x50,
	0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x0b, 0x70, 0x61, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x29,
	0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x44, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x48, 0x44, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x46, 0x10, 0x02, 0x2a, 0x34, 0x0a, 0x0c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x10, 0x02, 0x32,
	0x87, 0x02, 0x0a, 0x0b, 0x46, 0x61, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x12, 0x17, 0x2e,
	0x66, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x3e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x12, 0x17, 0x2e,
	0x66, 0x61, 0x72, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x3e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x12, 0x17, 0x2e,
	0x66, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x66, 0x61, 0x72,
	0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x66, 0x61, 0x72, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x66, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fare_proto_rawDescOnce sync.Once
	file_fare_proto_rawDescData = file_fare_proto_rawDesc
)

func file_fare_proto_rawDescGZIP() []byte {
	file_fare_proto_rawDescOnce.Do(func() {
		file_fare_proto_rawDescData = protoimpl.X.CompressGZIP(file_fare_proto_rawDescData)
	})
	return file_fare_proto_rawDescData
}

var file_fare_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fare_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fare_proto_goTypes = []interface{}{
	(PassageTypes)(0),              // 0: fare.PassageTypes
	(ServiceLevel)(0),              // 1: fare.ServiceLevel
	(*Result)(nil),                 // 2: fare.Result
	(*Fare)(nil),                   // 3: fare.Fare
	(*CreateFareRequest)(nil),      // 4: fare.CreateFareRequest
	(*CreateFareReply)(nil),        // 5: fare.CreateFareReply
	(*UpdateFareRequest)(nil),      // 6: fare.UpdateFareRequest
	(*UpdateFareReply)(nil),        // 7: fare.UpdateFareReply
	(*DeleteFareRequest)(nil),      // 8: fare.DeleteFareRequest
	(*DeleteFareReply)(nil),        // 9: fare.DeleteFareReply
	(*PricingRequest)(nil),         // 10: fare.PricingRequest
	(*PricingResponse)(nil),        // 11: fare.PricingResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil), // 13: google.protobuf.DoubleValue
}
var file_fare_proto_depIdxs = []int32{
	0,  // 0: fare.Fare.passage_type:type_name -> fare.PassageTypes
	12, // 1: fare.Fare.first_travel_date:type_name -> google.protobuf.Timestamp
	12, // 2: fare.Fare.last_travel_date:type_name -> google.protobuf.Timestamp
	13, // 3: fare.Fare.amount:type_name -> google.protobuf.DoubleValue
	3,  // 4: fare.CreateFareRequest.fare:type_name -> fare.Fare
	2,  // 5: fare.CreateFareReply.result:type_name -> fare.Result
	3,  // 6: fare.UpdateFareRequest.fare:type_name -> fare.Fare
	3,  // 7: fare.UpdateFareReply.fare:type_name -> fare.Fare
	12, // 8: fare.PricingRequest.flight_datetime:type_name -> google.protobuf.Timestamp
	0,  // 9: fare.PricingRequest.passage_type:type_name -> fare.PassageTypes
	2,  // 10: fare.PricingResponse.result:type_name -> fare.Result
	12, // 11: fare.PricingResponse.flight_datetime:type_name -> google.protobuf.Timestamp
	0,  // 12: fare.PricingResponse.passage_type:type_name -> fare.PassageTypes
	13, // 13: fare.PricingResponse.amount:type_name -> google.protobuf.DoubleValue
	4,  // 14: fare.FareService.CreateFare:input_type -> fare.CreateFareRequest
	6,  // 15: fare.FareService.UpdateFare:input_type -> fare.UpdateFareRequest
	8,  // 16: fare.FareService.DeleteFare:input_type -> fare.DeleteFareRequest
	10, // 17: fare.FareService.Pricing:input_type -> fare.PricingRequest
	5,  // 18: fare.FareService.CreateFare:output_type -> fare.CreateFareReply
	7,  // 19: fare.FareService.UpdateFare:output_type -> fare.UpdateFareReply
	9,  // 20: fare.FareService.DeleteFare:output_type -> fare.DeleteFareReply
	11, // 21: fare.FareService.Pricing:output_type -> fare.PricingResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_fare_proto_init() }
func file_fare_proto_init() {
	if File_fare_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fare_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PricingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fare_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PricingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fare_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fare_proto_goTypes,
		DependencyIndexes: file_fare_proto_depIdxs,
		EnumInfos:         file_fare_proto_enumTypes,
		MessageInfos:      file_fare_proto_msgTypes,
	}.Build()
	File_fare_proto = out.File
	file_fare_proto_rawDesc = nil
	file_fare_proto_goTypes = nil
	file_fare_proto_depIdxs = nil
}
