// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: price.proto

package price

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PassageTypes int32

const (
	PassageTypes_ADT PassageTypes = 0 //成人
	PassageTypes_CHD PassageTypes = 1 //儿童
	PassageTypes_INF PassageTypes = 2 //婴儿
)

// Enum value maps for PassageTypes.
var (
	PassageTypes_name = map[int32]string{
		0: "ADT",
		1: "CHD",
		2: "INF",
	}
	PassageTypes_value = map[string]int32{
		"ADT": 0,
		"CHD": 1,
		"INF": 2,
	}
)

func (x PassageTypes) Enum() *PassageTypes {
	p := new(PassageTypes)
	*p = x
	return p
}

func (x PassageTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PassageTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_price_proto_enumTypes[0].Descriptor()
}

func (PassageTypes) Type() protoreflect.EnumType {
	return &file_price_proto_enumTypes[0]
}

func (x PassageTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PassageTypes.Descriptor instead.
func (PassageTypes) EnumDescriptor() ([]byte, []int) {
	return file_price_proto_rawDescGZIP(), []int{0}
}

type ServiceLevel int32

const (
	ServiceLevel_First    ServiceLevel = 0 //头等
	ServiceLevel_Business ServiceLevel = 1 //公务
	ServiceLevel_Economy  ServiceLevel = 2 //经济
)

// Enum value maps for ServiceLevel.
var (
	ServiceLevel_name = map[int32]string{
		0: "First",
		1: "Business",
		2: "Economy",
	}
	ServiceLevel_value = map[string]int32{
		"First":    0,
		"Business": 1,
		"Economy":  2,
	}
)

func (x ServiceLevel) Enum() *ServiceLevel {
	p := new(ServiceLevel)
	*p = x
	return p
}

func (x ServiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_price_proto_enumTypes[1].Descriptor()
}

func (ServiceLevel) Type() protoreflect.EnumType {
	return &file_price_proto_enumTypes[1]
}

func (x ServiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceLevel.Descriptor instead.
func (ServiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_price_proto_rawDescGZIP(), []int{1}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//0 - 成功，其它 - 失败
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	//失败信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_price_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//机票销售价格计算请求
type PricingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//起飞机场
	OrgAirport string `protobuf:"bytes,1,opt,name=org_airport,json=orgAirport,proto3" json:"org_airport,omitempty"`
	//到达机场
	ArrAirport string `protobuf:"bytes,2,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	//航班日期
	FlightDatetime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=flight_datetime,json=flightDatetime,proto3" json:"flight_datetime,omitempty"`
	//乘客类型
	PassageType PassageTypes `protobuf:"varint,4,opt,name=passage_type,json=passageType,proto3,enum=price.PassageTypes" json:"passage_type,omitempty"`
}

func (x *PricingRequest) Reset() {
	*x = PricingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRequest) ProtoMessage() {}

func (x *PricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRequest.ProtoReflect.Descriptor instead.
func (*PricingRequest) Descriptor() ([]byte, []int) {
	return file_price_proto_rawDescGZIP(), []int{1}
}

func (x *PricingRequest) GetOrgAirport() string {
	if x != nil {
		return x.OrgAirport
	}
	return ""
}

func (x *PricingRequest) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *PricingRequest) GetFlightDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.FlightDatetime
	}
	return nil
}

func (x *PricingRequest) GetPassageType() PassageTypes {
	if x != nil {
		return x.PassageType
	}
	return PassageTypes_ADT
}

//机票销售价格计算结果
type PricingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//处理结果
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	//起飞机场
	OrgAirport string `protobuf:"bytes,2,opt,name=org_airport,json=orgAirport,proto3" json:"org_airport,omitempty"`
	//到达机场
	ArrAirport string `protobuf:"bytes,3,opt,name=arr_airport,json=arrAirport,proto3" json:"arr_airport,omitempty"`
	//航班日期
	FlightDatetime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=flight_datetime,json=flightDatetime,proto3" json:"flight_datetime,omitempty"`
	//乘客类型
	PassageType PassageTypes `protobuf:"varint,5,opt,name=passage_type,json=passageType,proto3,enum=price.PassageTypes" json:"passage_type,omitempty"`
	//价格
	Amount *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PricingResponse) Reset() {
	*x = PricingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PricingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingResponse) ProtoMessage() {}

func (x *PricingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingResponse.ProtoReflect.Descriptor instead.
func (*PricingResponse) Descriptor() ([]byte, []int) {
	return file_price_proto_rawDescGZIP(), []int{2}
}

func (x *PricingResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PricingResponse) GetOrgAirport() string {
	if x != nil {
		return x.OrgAirport
	}
	return ""
}

func (x *PricingResponse) GetArrAirport() string {
	if x != nil {
		return x.ArrAirport
	}
	return ""
}

func (x *PricingResponse) GetFlightDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.FlightDatetime
	}
	return nil
}

func (x *PricingResponse) GetPassageType() PassageTypes {
	if x != nil {
		return x.PassageType
	}
	return PassageTypes_ADT
}

func (x *PricingResponse) GetAmount() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_price_proto protoreflect.FileDescriptor

var file_price_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xcf, 0x01,
	0x0a, 0x0e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x67, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x67, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x72, 0x41, 0x69, 0x72, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xad, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72,
	0x67, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x72, 0x67, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x72, 0x72, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x72, 0x72, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x43, 0x0a, 0x0f,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x36, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e,
	0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x0b, 0x70, 0x61,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2a,
	0x29, 0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x48, 0x44, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x46, 0x10, 0x02, 0x2a, 0x34, 0x0a, 0x0c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x10, 0x02,
	0x32, 0x4a, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_proto_rawDescOnce sync.Once
	file_price_proto_rawDescData = file_price_proto_rawDesc
)

func file_price_proto_rawDescGZIP() []byte {
	file_price_proto_rawDescOnce.Do(func() {
		file_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_proto_rawDescData)
	})
	return file_price_proto_rawDescData
}

var file_price_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_price_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_price_proto_goTypes = []interface{}{
	(PassageTypes)(0),              // 0: price.PassageTypes
	(ServiceLevel)(0),              // 1: price.ServiceLevel
	(*Result)(nil),                 // 2: price.Result
	(*PricingRequest)(nil),         // 3: price.PricingRequest
	(*PricingResponse)(nil),        // 4: price.PricingResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*wrapperspb.DoubleValue)(nil), // 6: google.protobuf.DoubleValue
}
var file_price_proto_depIdxs = []int32{
	5, // 0: price.PricingRequest.flight_datetime:type_name -> google.protobuf.Timestamp
	0, // 1: price.PricingRequest.passage_type:type_name -> price.PassageTypes
	2, // 2: price.PricingResponse.result:type_name -> price.Result
	5, // 3: price.PricingResponse.flight_datetime:type_name -> google.protobuf.Timestamp
	0, // 4: price.PricingResponse.passage_type:type_name -> price.PassageTypes
	6, // 5: price.PricingResponse.amount:type_name -> google.protobuf.DoubleValue
	3, // 6: price.PriceService.Pricing:input_type -> price.PricingRequest
	4, // 7: price.PriceService.Pricing:output_type -> price.PricingResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_price_proto_init() }
func file_price_proto_init() {
	if File_price_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PricingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PricingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_proto_goTypes,
		DependencyIndexes: file_price_proto_depIdxs,
		EnumInfos:         file_price_proto_enumTypes,
		MessageInfos:      file_price_proto_msgTypes,
	}.Build()
	File_price_proto = out.File
	file_price_proto_rawDesc = nil
	file_price_proto_goTypes = nil
	file_price_proto_depIdxs = nil
}
